spring:
  config:
    import: "optional:dotenv:"

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        open-in-view: false
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:30MB}
      max-request-size: ${MAX_REQUEST_SIZE:30MB}
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}

  kakao:
    client-id: ${REST_API_KEY}
    redirect-uri: http://43.203.72.240:8080/auth/login/code/kakao
    scope: profile_nickname
    authorization-uri: https://kauth.kakao.com/oauth/authorize
    token-uri: https://kauth.kakao.com/oauth/token
    user-info-uri: https://kapi.kakao.com/v2/user/me

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs
    path: /swagger-ui
    server:
      local: ${LOCAL_SERVER_URL:http://localhost:8080}
      main: ${MAIN_SERVER_URL}

logging:
  level:
    root: ${LOG_LEVEL:INFO}
    com.example: ${LOG_LEVEL_COM_EXAMPLE:DEBUG}

cloud:
  aws:
    s3:
      bucket: yechef-bucket
    region:
      static: ap-northeast-2
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
